backend:
  name: github
  repo: iamhmza/gridsome-jamstack

media_folder: 'static/uploads'
public_folder: '/ulpoads'

collections:
  - name: post
    label: post
    folder: 'content/blog'
    create: true
    slug: '{ { slug } }'
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: date }
      - { label: Content, name: content, widget: markdown }
